### ISSUE TITLE
ellipse N config file

### ISSUE THREAD

**Issue by d3637042** [ENSTABretagneRobotics/sbg_ros_driver#10]
Hi, I'm using this package to run my ellipse N. I tried to change the parameters in the example config file but when I run the program it didn't output messages that start with gps. I'm wondering if I didn't setup the right parameters in my config file, could you help me check it? Thanks
https://drive.google.com/file/d/1bciL6XCjIcN1GnJzgSD-kh17b1MQ2sLB/view?usp=sharing

**Comment by ThomasLeMezo** [comment]
Hi @d3637042,
Your config file seems to be correct. You should try your configuration with the SBG Center software to check if your gps is working and/or ask SBG Support.
