### ISSUE TITLE
std::put_time is not available on Debian Jessie

### ISSUE THREAD

**Issue by tfoote** [ENSTABretagneRobotics/sbg_ros_driver#6]
Builds of sbg_ros_driver are failing on Debian Jessie due to missing std::put_time

http://repositories.ros.org/status_page/ros_kinetic_dj.html?q=REGRESSION
http://repositories.ros.org/status_page/ros_kinetic_djv8.html?q=REGRESSION

For example: http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__sbg_driver__debian_jessie_amd64__binary/107/console
```
23:11:47 /tmp/binarydeb/ros-kinetic-sbg-driver-1.1.6/src/ellipse.cpp: In member function ‘bool Ellipse::end_mag_calibration()’:
23:11:47 /tmp/binarydeb/ros-kinetic-sbg-driver-1.1.6/src/ellipse.cpp:849:10: error: ‘put_time’ is not a member of ‘std’
23:11:47    oss << std::put_time(&tm, "mag_calib_%Y_%m_%d-%Hh%Mmin%Ss.txt");
23:11:47           ^
23:11:47 make[4]: *** [CMakeFiles/ellipse.dir/src/ellipse.cpp.o] Error 1
23:11:47 CMakeFiles/ellipse.dir/build.make:80: recipe for target 'CMakeFiles/ellipse.dir/src/ellipse.cpp.o' failed
```

I believe that the c++ version available in Jessie doesn't have support for that method
http://en.cppreference.com/w/cpp/io/manip/put_time

We're preparing a Kinetic sync: https://discourse.ros.org/t/preparing-for-kinetic-sync-2018-06-06/5034

I'd usually let this regress and move on but since this will be the last sync for Jessie wanted to ping a little bit more agressively. If you're not using it on Jessie and don't have any users on Jessie that's fine too. Supporting this will not be necessary after this sync, and this can just be closed.

**Comment by ThomasLeMezo** [comment]
Thanks for the report. I know the issue but I didn't find an other function to do that until today. I have just committed a new way to do that using the same method as in rosbag for file naming... I will test soon if it works on a real system.
