### ISSUE TITLE
frequency parameter is ignored

### ISSUE THREAD

**Issue by nicolaje** [ENSTABretagneRobotics/sbg_ros_driver#7]
Hello Thomas,

no matter what the value of "frequency" is, the IMU will output data at a 25Hz rate.

Seems to me that this parameter is never actually sent to the IMU anyway, and is just used to set the "rate" object.

I guess the fix should happen around here:
https://github.com/ENSTABretagneRobotics/sbg_ros_driver/blob/f56ede11bcf29f3456e50a4565ac6baaff6d2d11/src/ellipse.cpp#L647

@+

Jeremy

**Comment by ThomasLeMezo** [comment]
Hello Jeremy,
The parameter "frequency" is the ros node frequency at which data is published. It is not the frequency of IMU msg. You should instead set the desired frequency for each message in the config file (see below). The "frequency" parameter is normally auto-set to the highest frequency of the output IMU msg.
https://github.com/ENSTABretagneRobotics/sbg_ros_driver/blob/e49f864cd1f249d28b17abc241c515198cbc6c11/config/ellipse_A_default.yaml#L199-L260
